steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/abscotek-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/abscotek-backend:latest'
      - '.'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/abscotek-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/abscotek-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'abscotek-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/abscotek-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5832'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '900'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--service-account'
      - 'YOUR_SERVICE_ACCOUNT@YOUR_PROJECT.iam.gserviceaccount.com'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/abscotek-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/abscotek-backend:latest'

# Set timeout
timeout: '1200s'